#!/bin/bash

bar_height=20
horizontal_padding=7
cursor_height=14
font="Terminess Nerd Font Propo 9"
normbg="#242b38"
normfg="#abb2bf"
selbg="#4fa6ed"
selfg="#242b38"

export BEMENU_OPTS="-H $bar_height --fn '$font' --nb $normbg --fb $normbg --cb $normbg --ab $normbg --tb $normbg --nf $normfg --ff $normfg --cf $normfg --af $normfg --tf $normfg --hb $selbg --hf $selfg --hp $horizontal_padding"
