#!/bin/bash
bh=25                   # Height of the menu bar
hp=10                   # Horizontal padding
ch=20                   # Height of the cursor
list_items=20           # Number of list items to show
width_factor=0.5        # Width factor relative to the screen width
border_px=1             # Border size
border_radius=10        # Border radius
margin_px=40            # Margin size
fn="MonaspiceRn NF 10"  # Font and size
ab="#303446"            # Active background
af="#c6d0f5"            # Active foreground
fb="#303446"            # Focused background
ff="#c6d0f5"            # Focused foreground
hb="#546288"            # Highlighted background
hf="#303446"            # Highlighted foreground
nb="#303446"            # Normal background
nf="#c6d0f5"            # Normal foreground
tb="#303446"            # Title background
tf="#e78284"            # Title foreground
bdr="#546288"           # Border color

export BEMENU_OPTS="
  --counter always
  --list $list_items
  --center
  --no-cursor
  --no-touch
  --border $border_px
  --border-radius $border_radius
  --margin $margin_px
  --width-factor $width_factor
  --fixed-height
  -H $bh
  --fn '$fn'
  --ab $ab
  --af $af
  --fb $fb
  --ff $ff
  --hb $hb
  --hf $hf
  --nb $nb
  --nf $nf
  --tb $tb
  --tf $tf
  --hp $hp
  --ch $ch
  --bdr $bdr"
