scrolling:
  history: 10000

font:
  normal:
    family: UbuntuMono Nerd Font
    style: Regular
  bold:
    family: UbuntuMono Nerd Font
    style: Regular
  size: 10

window:
  decorations: none
  dynamic_padding: true
  dynamic_title: true

colors:
  # Default colors
  primary:
    background: '#242b38'
    foreground: '#abb2bf'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x292d3e'
    cursor: '0xffffff'
    blinking: off

  # Normal colors
  normal:
    # NOTE: Use '#131613' for the `black` color if you'd like to see
    # black text on the background.
    black:   '#282c34'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#abb2bf'

  # Bright colors
  bright:
    black:   '#5c6370'
    red:     '#e06c75'
    green:   '#98c379'
    yellow:  '#d19a66'
    blue:    '#61afef'
    magenta: '#c678dd'
    cyan:    '#56b6c2'
    white:   '#ffffff'

mouse:
  hide_when_typing: true

  indexed_colors:
    - { index: 16, color: '0xf78c6c' }
    - { index: 17, color: '0xff5370' }
    - { index: 18, color: '0x444267' }
    - { index: 19, color: '0x32374d' }
    - { index: 20, color: '0x8796b0' }
    - { index: 21, color: '0x959dcb' }

key_bindings:
  - { key: T,         mods: Control|Shift, action: SpawnNewInstance    }
  - { key: Insert,    mods: Shift,         action: PasteSelection      }
  - { key: Insert,    mods: Control,       action: Copy                }
  - { key: Key0,      mods: Control,       action: ResetFontSize       }
  - { key: PageUp,    mods: Control,       action: IncreaseFontSize    }
  - { key: PageDown,  mods: Control,       action: DecreaseFontSize    }
