scrolling:
  history: 10000

font:
  normal:
    family: canele
    style: Regular
  
  bold:
    family: canele
    style: Regular
  
  size: 9

# Base16 Material Palenight 256 - alacritty color config
# Nate Peterson
colors:
  # Default colors
  primary:
    background: '0x292d3e'
    foreground: '0xffffff'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x292d3e'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x292d3e'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0x959dcb'

  # Bright colors
  bright:
    black:   '0x676e95'
    red:     '0xf07178'
    green:   '0xc3e88d'
    yellow:  '0xffcb6b'
    blue:    '0x82aaff'
    magenta: '0xc792ea'
    cyan:    '0x89ddff'
    white:   '0xffffff'

mouse:
  hide_when_typing: true

  indexed_colors:
    - { index: 16, color: '0xf78c6c' }
    - { index: 17, color: '0xff5370' }
    - { index: 18, color: '0x444267' }
    - { index: 19, color: '0x32374d' }
    - { index: 20, color: '0x8796b0' }
    - { index: 21, color: '0x959dcb' }

key_bindings:
  - { key: T,      mods: Control|Shift, action: SpawnNewInstance }
  - { key: Insert, mods: Shift,         action: PasteSelection   }
  - { key: Insert, mods: Control,       action: Copy             }
