#!/bin/bash
# Gruvbox dark, medium PS1 prompt with git support and OSC7 CWD support
# Generated by chclr - do not edit manually, changes will be overwritten.
# Install by sourcing this file from your ~/.bashrc.

# Gruvbox dark, medium colors
CHCLR_ROSEWATER="\[\e[38;2;235;219;178m\]"
CHCLR_FLAMINGO="\[\e[38;2;214;93;14m\]"
CHCLR_PINK="\[\e[38;2;222;164;180m\]"
CHCLR_MAUVE="\[\e[38;2;211;134;155m\]"
CHCLR_RED="\[\e[38;2;251;73;52m\]"
CHCLR_MAROON="\[\e[38;2;233;83;33m\]"
CHCLR_PEACH="\[\e[38;2;254;128;25m\]"
CHCLR_YELLOW="\[\e[38;2;250;189;47m\]"
CHCLR_GREEN="\[\e[38;2;184;187;38m\]"
CHCLR_TEAL="\[\e[38;2;142;192;124m\]"
CHCLR_SKY="\[\e[38;2;164;204;150m\]"
CHCLR_SAPPHIRE="\[\e[38;2;137;179;138m\]"
CHCLR_BLUE="\[\e[38;2;131;165;152m\]"
CHCLR_LAVENDER="\[\e[38;2;251;241;199m\]"
CHCLR_TEXT="\[\e[38;2;213;196;161m\]"
CHCLR_SUBTEXT1="\[\e[38;2;208;192;158m\]"
CHCLR_SUBTEXT0="\[\e[38;2;205;188;156m\]"
CHCLR_OVERLAY2="\[\e[38;2;201;185;154m\]"
CHCLR_OVERLAY1="\[\e[38;2;196;181;151m\]"
CHCLR_OVERLAY0="\[\e[38;2;193;177;149m\]"
CHCLR_SURFACE2="\[\e[38;2;189;174;147m\]"
CHCLR_SURFACE1="\[\e[38;2;102;92;84m\]"
CHCLR_SURFACE0="\[\e[38;2;80;73;69m\]"
CHCLR_BASE="\[\e[38;2;40;40;40m\]"
CHCLR_MANTLE="\[\e[38;2;60;56;54m\]"
CHCLR_CRUST="\[\e[38;2;51;48;46m\]"

# Style attributes
BOLD="\[\e[1m\]"
RESET="\[\e[0m\]"

# Git functions
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

parse_git_status() {
    local status=$(git status --porcelain 2> /dev/null)

    if [[ -z "$status" ]]; then
        echo "clean"
    else
        echo "dirty"
    fi
}

# Function to update the OSC7 working directory
update_osc7_cwd() {
    # Get the current working directory as a file:// URI
    local pwd_uri="file://$HOSTNAME${PWD}"
    # Send the OSC7 escape sequence
    printf "\e]7;%s\a" "$pwd_uri"
}

# Function to set the PS1 prompt
# Accepts one optional argument: the exit code of the previously executed command.
set_ps1() {
    local exit_code=${1:-0}

    # Update OSC7 after capturing the exit code
    update_osc7_cwd

    local exit_status=""
    # Add exit code indicator if non-zero AND not 130 (Ctrl+C)
    if [ "$exit_code" -ne 0 ] && [ "$exit_code" -ne 130 ]; then
        exit_status="${CHCLR_RED}✗ $exit_code ${RESET}"
    fi

    # Basic prompt parts with bold username and hostname
    local user_host="${CHCLR_LAVENDER}${BOLD}\u${RESET}${CHCLR_SURFACE2}@${CHCLR_BLUE}${BOLD}\h${RESET}"
    local current_dir="${CHCLR_SAPPHIRE}\w${RESET}"
    local prompt_char="${CHCLR_GREEN}\$${RESET}"

    # Git part
    local git_info=""
    local git_branch=$(parse_git_branch)

    if [ -n "$git_branch" ]; then
        local git_status=$(parse_git_status)
        local branch_color="${CHCLR_MAUVE}"
        local status_indicator=""

        if [ "$git_status" == "dirty" ]; then
            status_indicator=" ${CHCLR_PEACH}✱${RESET}"
        else
            status_indicator=" ${CHCLR_GREEN}✓${RESET}"
        fi

        git_info="${CHCLR_SURFACE2} on ${branch_color}󰘬 ${git_branch}${status_indicator}${RESET}"
    fi

    # Time part
    local time_part="${CHCLR_SURFACE2}[${CHCLR_YELLOW}\t${CHCLR_SURFACE2}]${RESET}"

    # Build PS1
    PS1="${exit_status}${time_part} ${user_host} ${current_dir}${git_info} ${prompt_char} "
}

# Install a PROMPT_COMMAND wrapper that:
# - captures the previous command's exit code,
# - preserves any existing PROMPT_COMMAND (runs it),
# - then calls set_ps1 with the captured exit code.
if [[ $- == *i* ]]; then  # only for interactive shells
    if [[ -z "${__chclr_prompt_installed:-}" ]]; then
        __chclr_prompt_installed=1
        __chclr_saved="${PROMPT_COMMAND:-}"

        __chclr_prompt_command() {
            # Capture the exit code of the previously executed command immediately.
            local last_exit=$?

            # If there was an existing PROMPT_COMMAND before we installed ourselves,
            # run it first so we don't lose any functionality the user or other scripts expect.
            if [[ -n "${__chclr_saved:-}" ]]; then
                # eval is used to execute the saved command string.
                eval "${__chclr_saved}"
            fi

            # Now assemble PS1 using the saved exit code
            set_ps1 "$last_exit"
        }

        PROMPT_COMMAND="__chclr_prompt_command"
    fi
fi
