#!/bin/bash
shopt -s extglob

# Author Daniel Vigh #
rm -rf configs
echo -e "Creating backup from packages..."
pacman -Qmq > "aur.pkgs"
pacman -Qeq | grep -v "$(pacman -Qmq)" > "pacman.pkgs"
systemctl list-unit-files --type=service --state=enabled --no-legend | cut -d ' ' -f1 | grep -v getty > "enabled_services"
echo -e "Creating backup from configs...\n"
CONFIGS=(
  "$HOME/.bashrc"
  "$HOME/.bash_profile"
  "$HOME/.dircolors"
  "$HOME/.dircolors_256"
  "$HOME/.fonts.conf"
  "$HOME/.fonts/"
  "$HOME/.fonts.conf"
  "$HOME/.gitconfig"
  "$HOME/.gtkrc-2.0"
  "$HOME/.inputrc"
  "$HOME/.vifm"
  "$HOME/.vimrc"
  "$HOME/.xinitrc"
  "$HOME/.moc"
  "$HOME/.asoundrc"
  "$HOME/.config/termite/config"
  /etc/iwd/main.conf
  /etc/makepkg.conf
  /etc/mkinitcpio.conf
  /etc/modprobe.d/
  /etc/sysctl.d/
  /etc/pacman.conf
  /etc/pacman.d/mirrorlist
  /etc/X11/xorg.conf
  /etc/systemd/system/trackpoint_parameters.service
  /usr/local/bin/trackpoint_configuration.sh
  /usr/local/bin/dwm-statusbar
)
[ ! -e "configs" ] && mkdir "configs"
rm -rf "configs/*"
for f in "${CONFIGS[@]}"; do echo "Backing up of $f..."; rsync -Rr "$f" "configs/"; done
[ -d "configs/home/$USER/.local/share/vifm/Trash" ] && "rm -rf configs/home/$USER/.local/share/vifm/Trash"
[ -f "configs/home/$USER/.bashrc" ] && \
  sed -i '/vighd/d' "configs/home/$USER/.bashrc"

# Cleaning unneeded files
find configs/home/vighd/.moc/ -mindepth 1 ! -name 'config' ! -name 'keymap' -exec 'rm' {} \;
rm configs/home/vighd/.vifm/vifminfo.json

echo -e "\nDone."
