#!/bin/bash
# shellcheck disable=SC2015
# shellcheck disable=SC2235
# shellcheck disable=SC2181
# shellcheck disable=SC2162
# shellcheck disable=SC2199
#
# Author Daniel Vigh #
echo -e "Creating backup from packages..."
pacman -Qmq > "aur.pkgs"
pacman -Qeq | grep -v "$(pacman -Qmq)" > "pacman.pkgs"
systemctl list-unit-files --type=service --state=enabled --no-legend | cut -d ' ' -f1 | grep -v getty > "enabled_services"
echo -e "Creating backup from configs...\n"
CONFIGS=(
  "$HOME/.bashrc"
  "$HOME/.bash_profile"
  "$HOME/.dircolors"
  "$HOME/.dircolors_256"
  "$HOME/.fonts.conf"
  "$HOME/.fonts/"
  "$HOME/.fonts.conf"
  "$HOME/.gitconfig"
  "$HOME/.gtkrc-2.0"
  "$HOME/.inputrc"
  "$HOME/.vifm"
  "$HOME/.vimrc"
  "$HOME/.xinitrc"
  "$HOME/.asoundrc"
  "$HOME/.config/termite"
  /etc/iwd/main.conf
  /etc/makepkg.conf
  /etc/mkinitcpio.conf
  /etc/modprobe.d/
  /etc/sysctl.d/
  /etc/pacman.conf
  /etc/pacman.d/mirrorlist
  /etc/X11/xorg.conf.d/99-input.conf
  /etc/X11/xorg.conf.d/20-intel.conf
  /etc/X11/xorg.conf.d/10-monitor.conf
  /etc/systemd/system/trackpoint_parameters.service
  /usr/local/bin/trackpoint_configuration.sh
  /usr/local/bin/dwm-statusbar
)
[ ! -e "configs" ] && mkdir "configs"
rm -rf "configs/*"
for f in "${CONFIGS[@]}"; do echo "Backing up of $f..."; rsync -Rr "$f" "configs/"; done
[ -d "configs/home/$USER/.local/share/vifm/Trash" ] && "rm -rf configs/home/$USER/.local/share/vifm/Trash"
[ -f "configs/home/$USER/.bashrc" ] && \
  sed -i '/vighd/d' "configs/home/$USER/.bashrc"

echo -e "\nDone."
