#!/bin/bash

#
# Input configuration
#
riverctl keyboard-layout          hu
riverctl focus-follows-cursor     always
riverctl set-repeat               45 300
riverctl hide-cursor when-typing  enabled
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad events disabled
riverctl input pointer-2-14-ETPS/2_Elantech_TrackPoint accel-profile none
riverctl input pointer-2-14-ETPS/2_Elantech_TrackPoint pointer-accel -0.2

#
# Key bindings
#
# Spawn things
riverctl map normal Alt         P                       spawn 'source $HOME/.config/bemenu/config; bemenu-run -p "RUN"'
riverctl map normal Alt+Shift   B                       spawn 'source $HOME/.config/bemenu/config; bemenu-bluetooth -p "BLUETOOTH"'
riverctl map normal Alt         I                       spawn 'source $HOME/.config/bemenu/config; pass-bemenu -p "PASSWORD"'
riverctl map normal Alt         O                       spawn 'source $HOME/.config/bemenu/config; pass-bemenu --otp -p "OTP"'
riverctl map normal Alt+Shift   Return                  spawn 'foot'
riverctl map normal Alt+Shift   N                       spawn '/usr/local/bin/iwmenu-bemenu'
riverctl map normal Alt+Shift   F                       spawn 'foot -e vifm'
riverctl map normal Alt+Shift   S                       spawn 'foot -e pulsemixer'
riverctl map normal Alt+Shift   W                       spawn 'chromium'
riverctl map normal Super       L                       spawn 'swaylock -p -c 000000'
riverctl map normal Super       G                       spawn 'grep performance /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor > /dev/null && sudo tlp bat || sudo tlp ac'
riverctl map normal None        Print                   spawn 'grim -g "$(slurp)"'
riverctl map normal None        XF86AudioMute           spawn 'wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle'
riverctl map normal None        XF86AudioLowerVolume    spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- -l 1.2'
riverctl map normal None        XF86AudioRaiseVolume    spawn 'wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+ -l 1.2'
riverctl map normal None        XF86AudioMicMute        spawn 'pactl set-source-mute @DEFAULT_SOURCE@ toggle'
riverctl map normal None        XF86MonBrightnessDown   spawn 'brightnessctl set 5%-'
riverctl map normal None        XF86MonBrightnessUp     spawn 'brightnessctl set 5%+'
riverctl map normal None        XF86Display             spawn 'wlopm --toggle eDP-1'

# Layout stuff
riverctl map normal Alt+Shift   C         close
riverctl map normal Alt+Shift   Q         exit
riverctl map normal Alt         Return    zoom
riverctl map normal Alt         J         focus-view next
riverctl map normal Alt         K         focus-view previous
riverctl map normal Alt         Period    focus-output next
riverctl map normal Alt         Comma     focus-output previous
riverctl map normal Alt+Shift   Period    send-to-output next
riverctl map normal Alt+Shift   Comma     send-to-output previous
riverctl map normal Alt         G         toggle-fullscreen
riverctl map normal Alt         F         toggle-float
riverctl map normal Alt         H         send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal Alt         L         send-layout-cmd rivercarro "main-ratio +0.05"
riverctl map normal Alt         S         send-layout-cmd rivercarro "main-location left"
riverctl map normal Alt         T         send-layout-cmd rivercarro "main-location bottom"
riverctl map normal Alt         M         send-layout-cmd rivercarro "main-location monocle"
riverctl map normal None        Caps_Lock None
for i in $(seq 1 6)
do
    tags=$((1 << ($i - 1)))
    # Alt+[1-6] to focus tag [0-5]
    riverctl map normal Alt       $i set-focused-tags $tags
    # Alt+Shift+[1-6] to tag focused view with tag [0-5]
    riverctl map normal Alt+Shift $i set-view-tags    $tags
done

#
# Mouse bindings
#
riverctl map-pointer normal Alt         BTN_LEFT    move-view
riverctl map-pointer normal Alt         BTN_RIGHT   resize-view
riverctl map-pointer normal Alt         BTN_MIDDLE  toggle-float
riverctl map-pointer normal Alt+Shift   BTN_MIDDLE send-to-output next

#
# Colors
#
riverctl background-color       0x242b38
riverctl border-color-focused   0x425b80
riverctl border-color-unfocused 0x3e4452

#
# Ui
#
riverctl border-width     1
riverctl default-layout   rivercarro
riverctl xcursor-theme    "X11-Default-Black"
gsettings set org.gnome.desktop.interface       gtk-theme           "OneDarkCool"
gsettings set org.gnome.desktop.interface       icon-theme          "Numix"
gsettings set org.gnome.desktop.interface       cursor-theme        "X11-Default-Black"
gsettings set org.gnome.desktop.interface       document-font-name  "Ubuntu 11"
gsettings set org.gnome.desktop.interface       font-name           "Ubuntu 11"
gsettings set org.gnome.desktop.interface       monospace-font-name 'Ubuntu Mono 13'
gsettings set org.gnome.desktop.interface       font-antialiasing   "grayscale"
gsettings set org.gnome.desktop.interface       font-hinting        "slight"
gsettings set org.gnome.desktop.wm.preferences  button-layout   ""

#
# Filters
#
riverctl rule-add -title "Open File" float
riverctl rule-add -title "Save File" float
riverctl rule-add -title "Save As" float
riverctl rule-add -title "Open Folder" float
riverctl rule-add -title "Open As" float
riverctl rule-add -title "anydesk" float
riverctl rule-add -title "AnyDesk" float
riverctl rule-add -title "World of Warcraft" float

# Start layout generator(s)
rivercarro -outer-gaps 0 -inner-gaps 0 &

# Start Waybar
waybar &

# Output manger
way-displays > /tmp/way-displays.${XDG_VTNR}.${USER}.log 2>&1 &

# Ilde manager
sway-audio-idle-inhibit &
swayidle -w timeout 600 'swaylock -p -c 000000' &

# Set wallpaper
swaybg -i /home/vighd/Pictures/wp.png &

# Fix interop
systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP PATH
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
/usr/lib/xdg-desktop-portal-gtk &
/usr/lib/xdg-desktop-portal-wlr &

# Mount daemon
udiskie -q &
