# -*- conf -*-

font=MonaspiceRn NFM:size=10
#font=Terminess Nerd Font Mono:size=10
#font-bold=Terminess Nerd Font Mono:size=9
#font-italic=Terminess Nerd Font Mono:size=10
dpi-aware=no
workers=4
pad=10x10 center

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

[colors-dark]
alpha=1.0
cursor=33302e d5c4a1
foreground=d5c4a1
background=282828

## Normal/regular colors (color palette 0-7)
regular0=282828 # black (base)
regular1=fb4934 # red
regular2=b8bb26 # green
regular3=fabd2f # yellow
regular4=83a598 # blue
regular5=bdae93 # magenta (mauve)
regular6=83a598 # cyan
regular7=d5c4a1 # white (text)

## Bright colors (color palette 8-15)
bright0=504945 # bright black (surface0)
bright1=fb4934 # bright red
bright2=b8bb26 # bright green
bright3=fabd2f # bright yellow
bright4=83a598 # bright blue
bright5=bdae93 # bright magenta (mauve)
bright6=83a598 # bright cyan
bright7=d5c4a1 # bright white (lavender)

## The remaining 256-color palette
16=bdae93
17=d5c4a1

## Misc colors
selection-foreground=d5c4a1
selection-background=4f5369
urls=8be9fd
search-box-no-match=33302e fb4934
search-box-match=d5c4a1 504945
jump-labels=33302e bdae93
urls=83a598

[key-bindings]
font-increase=Control+Shift+Page_Up
font-decrease=Control+Shift+Page_Down
font-reset=Control+Shift+Home
spawn-terminal=Control+Shift+t

[mouse-bindings]
font-reset=Control+BTN_MIDDLE

# vim: ft=dosini
